local colors = require("zj-theme.colors")

describe("zj-theme.colors", function()
  describe("hl_colors", function()
    it("returns Normal's bg/fg formatted as #rrggbb", function()
      vim.api.nvim_set_hl(0, "Normal", { bg = 0x1a1b26, fg = 0xc0caf5 })
      local bg, fg = colors.hl_colors()
      assert.equals("#1a1b26", bg)
      assert.equals("#c0caf5", fg)
    end)

    it("returns nil, nil when Normal has no bg/fg set", function()
      vim.api.nvim_set_hl(0, "Normal", {})
      local bg, fg = colors.hl_colors()
      assert.is_nil(bg)
      assert.is_nil(fg)
    end)
  end)
end)
